use std::{collections::HashSet, sync::Arc};

use axum::{
    extract::{Extension, State},
    http::{header::HeaderName, HeaderValue, StatusCode},
    response::{IntoResponse, Json, Response},
};
use chrono::Utc;
use serde::Serialize;
use serde_json::json;
use tracing::{info, warn};
use uuid::Uuid;

use crate::{
    auth::AuthContext,
    fuel::{self, FuelEventPayload},
    middleware::RequestContext,
    models::{
        DraftAst, DraftAuthor, DraftConstraints, DraftDiagnostic, DraftIntentionV1, DraftQuestion,
        DraftScope, DraftSource, ErrorResponseV1, EvidenceItem, FuelDiffRouteRequestV1,
        GateDecisionV1, HealthResponse, IntentionDraftRequestV1, OpinionProposal, OpinionSignalV1,
        PrRiskRequestV1, RollbackPlanV1, RollbackTarget,
    },
    policy::PolicyInput,
    AppState,
};

const GATE_DECISION_HEADER: &str = "x-gate-decision";
const GATE_POLICY_HEADER: &str = "x-gate-policy";
const RESPONSE_ENVELOPE_SCHEMA: &str =
    "https://logline.world/schemas/response-envelope.v1.schema.json";

pub async fn health(Extension(req_ctx): Extension<RequestContext>) -> Json<HealthResponse> {
    Json(HealthResponse {
        request_id: req_ctx.request_id,
        output_schema: RESPONSE_ENVELOPE_SCHEMA,
        status: "ok",
    })
}

pub async fn draft_intention(
    State(state): State<Arc<AppState>>,
    Extension(auth): Extension<AuthContext>,
    Extension(req_ctx): Extension<RequestContext>,
    Json(input): Json<IntentionDraftRequestV1>,
) -> impl IntoResponse {
    if input.version != "intention.draft.request.v1" {
        return (
            StatusCode::BAD_REQUEST,
            Json(ErrorResponseV1::new(
                Some(req_ctx.request_id.clone()),
                "invalid_request",
                "Unsupported version; expected intention.draft.request.v1",
            )),
        )
            .into_response();
    }

    let lower = input.intent_text.to_lowercase();
    let inferred_high_risk = ["migration", "auth", "billing", "infra", "permission"]
        .iter()
        .any(|needle| lower.contains(needle));

    let risk_tier = input
        .context
        .constraints_hint
        .as_ref()
        .and_then(|hint| hint.risk_tier.clone())
        .unwrap_or_else(|| {
            if inferred_high_risk {
                "HIGH".into()
            } else {
                "LOW".into()
            }
        });

    let max_files_changed = input
        .context
        .constraints_hint
        .as_ref()
        .and_then(|hint| hint.max_files_changed)
        .unwrap_or(60)
        .clamp(1, 200);

    let max_diff_lines = input
        .context
        .constraints_hint
        .as_ref()
        .and_then(|hint| hint.max_diff_lines)
        .unwrap_or(1200)
        .clamp(1, 20000);

    let requires_human_review = risk_tier != "LOW";
    let strategy = if requires_human_review {
        "REVERT_PR"
    } else {
        "FEATURE_FLAG"
    }
    .to_string();

    let source_kind = input
        .context
        .source
        .as_ref()
        .map(|s| s.kind.clone())
        .unwrap_or_else(|| "api".into());

    let source_ref = input.context.source.as_ref().and_then(|s| s.r#ref.clone());

    let mut questions = Vec::new();
    if input.intent_text.trim().len() < 40 {
        questions.push(DraftQuestion {
            id: "q1".into(),
            question: "Qual modulo principal deve receber a mudanca?".into(),
            field_target: "ast.scope.in".into(),
            choices: vec![],
        });
    }

    let mut diagnostics = vec![DraftDiagnostic {
        severity: "INFO".into(),
        code: "DRAFT-GENERATED".into(),
        message: "Draft intention generated by edge-control.".into(),
        fields: vec![],
        suggestion: None,
    }];

    let synthetic_reason_codes = build_intention_reason_codes(&lower, !questions.is_empty());
    let synthetic_signal = if questions.is_empty() {
        "ALLOW"
    } else {
        "ESCALATE"
    };
    let synthetic_confidence = if questions.is_empty() { 0.88 } else { 0.76 };

    let policy_input = PolicyInput {
        signal: synthetic_signal.to_string(),
        confidence: synthetic_confidence,
        reason_codes: synthetic_reason_codes.clone(),
        fields_present: field_set(["signal", "confidence"]),
    };
    let opinion_event_id = Uuid::new_v4().to_string();

    let gate_decision = state.policy_set.evaluate(
        "intention_drafting",
        &policy_input,
        &req_ctx.request_id,
        &opinion_event_id,
    );
    emit_gate_log(
        "intention_drafting",
        &gate_decision,
        &policy_input.reason_codes,
    );

    diagnostics.push(DraftDiagnostic {
        severity: "INFO".into(),
        code: "GATE-DECISION".into(),
        message: format!(
            "Gate decision={} policy={}",
            gate_decision.decision, gate_decision.policy
        ),
        fields: vec!["signal".into(), "confidence".into(), "reason_codes".into()],
        suggestion: Some("If decision is HUMAN, confirm draft before execution.".into()),
    });

    if gate_decision.decision == "NO" {
        return with_gate_headers(
            (
                StatusCode::UNPROCESSABLE_ENTITY,
                Json(ErrorResponseV1::new(
                    Some(req_ctx.request_id.clone()),
                    "gate_denied",
                    "Draft denied by deterministic policy gate",
                )),
            )
                .into_response(),
            &gate_decision,
        );
    }

    let response = DraftIntentionV1 {
        request_id: req_ctx.request_id.clone(),
        output_schema: "https://logline.world/schemas/draft-intention.v1.schema.json",
        version: "draft-intention.v1",
        draft_intention_id: format!("dft-{}", Uuid::new_v4()),
        created_at: Utc::now().to_rfc3339(),
        author: DraftAuthor {
            kind: "service",
            id: format!(
                "{}:{}:{}:{}",
                auth.subject,
                auth.app_id.clone().unwrap_or_else(|| "unknown-app".into()),
                auth.tenant_id
                    .clone()
                    .unwrap_or_else(|| "unknown-tenant".into()),
                auth.role.clone().unwrap_or_else(|| "unknown-role".into())
            ),
        },
        source: DraftSource {
            kind: source_kind,
            r#ref: source_ref,
        },
        ast: DraftAst {
            version: "intention.ast.v1",
            title: format!("Code change for {}", input.context.repo),
            goal: input.intent_text,
            scope: DraftScope {
                r#in: vec![format!(
                    "{}:{} implementation",
                    input.context.repo,
                    input
                        .context
                        .default_branch
                        .clone()
                        .unwrap_or_else(|| "main".into())
                )],
                out: vec!["Unrelated modules".into()],
            },
            acceptance_criteria: vec![
                "Behavior change is covered by test or explicit validation evidence.".into(),
                "CI required checks pass.".into(),
                "Linear issue contains plan and test instructions.".into(),
            ],
            constraints: DraftConstraints {
                risk_tier,
                max_files_changed,
                max_diff_lines,
                rollback_required: true,
                requires_human_review,
            },
            rollback: RollbackPlanV1 {
                version: "rollback-plan.v1",
                strategy,
                steps: vec![
                    "Revert merge commit or disable rollout flag.".into(),
                    "Re-run CI checks and smoke test critical path.".into(),
                ],
                verification: vec![
                    "Health checks return OK.".into(),
                    "Regression scenario no longer reproduces.".into(),
                ],
                target: Some(RollbackTarget {
                    kind: "pr".into(),
                    r#ref: "to-be-linked-after-pr".into(),
                }),
                time_lock_minutes: Some(0),
                requires_two_person_confirm: requires_human_review,
            },
        },
        diagnostics,
        questions,
    };

    if let Err(err) = emit_fuel_pair(
        &state,
        &auth,
        "llm.intention_drafted",
        "intention.draft.gate_decided",
        &opinion_event_id,
        &req_ctx.request_id,
        &policy_input.reason_codes,
        json!({
            "draft_intention_id": response.draft_intention_id.clone(),
            "signal": policy_input.signal,
            "confidence": policy_input.confidence
        }),
        &gate_decision,
    )
    .await
    {
        warn!(error=%err, trace_id=%req_ctx.request_id, "fuel emission failed for intention flow");
    }

    let response = json_response(StatusCode::OK, &response);
    with_gate_headers(response, &gate_decision)
}

pub async fn pr_risk(
    State(state): State<Arc<AppState>>,
    Extension(auth): Extension<AuthContext>,
    Extension(req_ctx): Extension<RequestContext>,
    Json(input): Json<PrRiskRequestV1>,
) -> impl IntoResponse {
    if input.version != "pr.risk.request.v1" {
        return (
            StatusCode::BAD_REQUEST,
            Json(ErrorResponseV1::new(
                Some(req_ctx.request_id.clone()),
                "invalid_request",
                "Unsupported version; expected pr.risk.request.v1",
            )),
        )
            .into_response();
    }

    let mut reason_codes = Vec::<String>::new();

    let joined_paths = input.touched_paths.join(" ").to_lowercase();
    if joined_paths.contains("auth") {
        reason_codes.push("touches_auth".into());
    }
    if joined_paths.contains("billing") {
        reason_codes.push("touches_billing".into());
    }
    if joined_paths.contains("permission") || joined_paths.contains("rbac") {
        reason_codes.push("touches_permissions".into());
    }
    if joined_paths.contains("migration") || joined_paths.contains("schema") {
        reason_codes.push("touches_migrations".into());
    }
    if joined_paths.contains(".github/workflows") {
        reason_codes.push("touches_workflows".into());
    }

    let total_lines = input.diff_stats.lines_added + input.diff_stats.lines_deleted;
    if input.diff_stats.files_changed > 20 || total_lines > 400 {
        reason_codes.push("diff_large".into());
        reason_codes.push("blast_radius_high".into());
    } else {
        reason_codes.push("diff_small".into());
        reason_codes.push("blast_radius_low".into());
    }

    if reason_codes.is_empty() {
        reason_codes.push("unknown_impact".into());
    }

    let has_sensitive = reason_codes.iter().any(|code| {
        matches!(
            code.as_str(),
            "touches_auth"
                | "touches_billing"
                | "touches_permissions"
                | "touches_migrations"
                | "touches_workflows"
        )
    });

    let (signal, confidence, note) = if has_sensitive {
        (
            "ESCALATE".to_string(),
            0.93,
            Some("Sensitive path detected; force human merge path.".to_string()),
        )
    } else if reason_codes.iter().any(|c| c == "blast_radius_high") {
        (
            "ESCALATE".to_string(),
            0.85,
            Some("Large blast radius; classify as substantial.".to_string()),
        )
    } else {
        (
            "ALLOW".to_string(),
            0.91,
            Some("Light change candidate; still requires CI evidence.".to_string()),
        )
    };

    let opinion = OpinionSignalV1 {
        request_id: req_ctx.request_id.clone(),
        output_schema: "https://logline.world/schemas/opinion-signal.v1.schema.json",
        version: "opinion-signal.v1",
        signal: signal.clone(),
        confidence,
        reason_codes: reason_codes.clone(),
        evidence: vec![EvidenceItem {
            kind: "metric".into(),
            r#ref: format!(
                "files_changed={},lines_added={},lines_deleted={}",
                input.diff_stats.files_changed,
                input.diff_stats.lines_added,
                input.diff_stats.lines_deleted
            ),
            quote: Some(format!(
                "repo={},pr_id={},base={},head={},snippets={},intent_ref={}",
                input.repo,
                input.pr_id,
                input.base_branch,
                input.head_branch,
                input.patch_snippets.len(),
                input
                    .intent_ref
                    .as_ref()
                    .and_then(|r| r.intention_id.clone().or(r.issue_id.clone()))
                    .unwrap_or_else(|| "none".into())
            )),
            score: Some(confidence),
        }],
        proposal: None,
        debug_note: note,
    };

    let policy_input = PolicyInput {
        signal,
        confidence,
        reason_codes,
        fields_present: field_set(["signal", "confidence", "pr_id"]),
    };
    let opinion_event_id = Uuid::new_v4().to_string();
    let gate_decision = state.policy_set.evaluate(
        "pr_risk",
        &policy_input,
        &req_ctx.request_id,
        &opinion_event_id,
    );
    emit_gate_log("pr_risk", &gate_decision, &policy_input.reason_codes);

    if let Err(err) = emit_fuel_pair(
        &state,
        &auth,
        "pr.risk.opinion_emitted",
        "pr.risk.gate_decided",
        &opinion_event_id,
        &req_ctx.request_id,
        &policy_input.reason_codes,
        json!({
            "pr_id": input.pr_id,
            "signal": policy_input.signal,
            "confidence": policy_input.confidence
        }),
        &gate_decision,
    )
    .await
    {
        warn!(error=%err, trace_id=%req_ctx.request_id, "fuel emission failed for pr_risk flow");
    }

    let response = json_response(StatusCode::OK, &opinion);
    with_gate_headers(response, &gate_decision)
}

pub async fn fuel_diff_route(
    State(state): State<Arc<AppState>>,
    Extension(auth): Extension<AuthContext>,
    Extension(req_ctx): Extension<RequestContext>,
    Json(input): Json<FuelDiffRouteRequestV1>,
) -> impl IntoResponse {
    if input.version != "fuel.diff.route.request.v1" {
        return (
            StatusCode::BAD_REQUEST,
            Json(ErrorResponseV1::new(
                Some(req_ctx.request_id.clone()),
                "invalid_request",
                "Unsupported version; expected fuel.diff.route.request.v1",
            )),
        )
            .into_response();
    }

    let mut reason_codes = Vec::<String>::new();

    for flag in &input.flags {
        let f = flag.to_lowercase();
        if f.contains("error") {
            reason_codes.push("error_spike".into());
        }
        if f.contains("latency") {
            reason_codes.push("latency_spike".into());
        }
        if f.contains("rate") {
            reason_codes.push("rate_limit_spike".into());
        }
        if f.contains("rollback") {
            reason_codes.push("rollback_increase".into());
        }
        if f.contains("cost") {
            reason_codes.push("cost_spike".into());
        }
    }

    if reason_codes.is_empty() {
        reason_codes.push("new_cluster_emerging".into());
    }

    let (signal, confidence) = if input.drift_score >= 1.0 {
        ("ALLOW".to_string(), 0.9)
    } else if input.drift_score >= 0.65 {
        ("ESCALATE".to_string(), 0.78)
    } else {
        ("DENY".to_string(), 0.62)
    };

    let proposal = if signal == "ALLOW" {
        Some(OpinionProposal {
            next: vec!["CREATE_DRAFT_INTENTION".into()],
            payload: json!({
                "from_snapshot_id": input.from_snapshot_id,
                "to_snapshot_id": input.to_snapshot_id,
                "drift_score": input.drift_score,
                "metric_deltas": input.metric_deltas,
            }),
        })
    } else {
        None
    };

    let opinion = OpinionSignalV1 {
        request_id: req_ctx.request_id.clone(),
        output_schema: "https://logline.world/schemas/opinion-signal.v1.schema.json",
        version: "opinion-signal.v1",
        signal: signal.clone(),
        confidence,
        reason_codes: reason_codes.clone(),
        evidence: vec![EvidenceItem {
            kind: "trace".into(),
            r#ref: format!(
                "fuel-diff:{}->{}",
                input.from_snapshot_id, input.to_snapshot_id
            ),
            quote: Some(format!(
                "drift_score={},evidence_refs={}",
                input.drift_score,
                input.evidence_refs.len()
            )),
            score: Some(confidence),
        }],
        proposal,
        debug_note: Some(
            "Deterministic diff pack routed by edge-control inference contract.".into(),
        ),
    };

    let policy_input = PolicyInput {
        signal,
        confidence,
        reason_codes,
        fields_present: field_set(["signal", "confidence"]),
    };
    let opinion_event_id = Uuid::new_v4().to_string();
    let gate_decision = state.policy_set.evaluate(
        "fuel_diff",
        &policy_input,
        &req_ctx.request_id,
        &opinion_event_id,
    );
    emit_gate_log("fuel_diff", &gate_decision, &policy_input.reason_codes);

    if let Err(err) = emit_fuel_pair(
        &state,
        &auth,
        "fuel.diff.opinion_emitted",
        "fuel.diff.gate_decided",
        &opinion_event_id,
        &req_ctx.request_id,
        &policy_input.reason_codes,
        json!({
            "from_snapshot_id": input.from_snapshot_id,
            "to_snapshot_id": input.to_snapshot_id,
            "drift_score": input.drift_score,
            "signal": policy_input.signal,
            "confidence": policy_input.confidence
        }),
        &gate_decision,
    )
    .await
    {
        warn!(error=%err, trace_id=%req_ctx.request_id, "fuel emission failed for fuel_diff flow");
    }

    let response = json_response(StatusCode::OK, &opinion);
    with_gate_headers(response, &gate_decision)
}

fn field_set<const N: usize>(keys: [&str; N]) -> HashSet<String> {
    keys.into_iter().map(ToString::to_string).collect()
}

fn build_intention_reason_codes(intent_lower: &str, has_questions: bool) -> Vec<String> {
    let mut reasons = Vec::new();

    if has_questions {
        reasons.push("ambiguous_request".into());
    }

    if intent_lower.contains("auth") {
        reasons.push("touches_auth".into());
    }
    if intent_lower.contains("billing") {
        reasons.push("touches_billing".into());
    }
    if intent_lower.contains("permission") {
        reasons.push("touches_permissions".into());
    }
    if intent_lower.contains("migration") || intent_lower.contains("schema") {
        reasons.push("touches_migrations".into());
    }
    if intent_lower.contains("infra") {
        reasons.push("touches_infra".into());
    }

    if reasons.is_empty() {
        reasons.push("local_ok".into());
    }

    reasons
}

fn emit_gate_log(domain: &str, gate: &GateDecisionV1, reason_codes: &[String]) {
    let gate_json = serde_json::to_string(gate).unwrap_or_else(|_| "{}".into());
    info!(
        domain=%domain,
        decision=%gate.decision,
        policy=%gate.policy,
        reason_codes=?reason_codes,
        gate_decision=%gate_json,
        "gate decision emitted"
    );
}

fn json_response<T: Serialize>(status: StatusCode, value: &T) -> Response {
    let mut response = (status, Json(value)).into_response();
    response.headers_mut().insert(
        HeaderName::from_static("content-type"),
        HeaderValue::from_static("application/json"),
    );
    response
}

fn with_gate_headers(mut response: Response, gate: &GateDecisionV1) -> Response {
    if let Ok(v) = HeaderValue::from_str(&gate.decision) {
        response
            .headers_mut()
            .insert(HeaderName::from_static(GATE_DECISION_HEADER), v);
    }
    if let Ok(v) = HeaderValue::from_str(&gate.policy) {
        response
            .headers_mut()
            .insert(HeaderName::from_static(GATE_POLICY_HEADER), v);
    }
    response
}

pub async fn orchestrate_intention_confirmed(
    State(state): State<Arc<AppState>>,
    Extension(auth): Extension<AuthContext>,
    Extension(req_ctx): Extension<RequestContext>,
    Json(input): Json<crate::orchestration::OrchestrateIntentionRequest>,
) -> impl IntoResponse {
    if let Err(err) = crate::orchestration::ensure_yes_human_1(&input.checkpoint) {
        return (
            StatusCode::BAD_REQUEST,
            Json(ErrorResponseV1::new(
                Some(req_ctx.request_id.clone()),
                "checkpoint_invalid",
                err.to_string(),
            )),
        )
            .into_response();
    }

    let intake = match crate::orchestration::call_code247_intentions(&state, &input).await {
        Ok(v) => v,
        Err(err) => {
            return (
                StatusCode::BAD_GATEWAY,
                Json(ErrorResponseV1::new(
                    Some(req_ctx.request_id.clone()),
                    "code247_unavailable",
                    err.to_string(),
                )),
            )
                .into_response();
        }
    };

    let issue_id = intake
        .linear
        .intentions
        .iter()
        .find(|i| i.id == input.intention_id)
        .map(|i| i.issue_id.clone());

    if let Err(err) = fuel::emit_event(
        &state,
        &auth,
        FuelEventPayload {
            event_id: None,
            event_type: "human.confirmed_intention".into(),
            trace_id: req_ctx.request_id.clone(),
            parent_event_id: None,
            outcome: "ok".into(),
            reason_codes: vec!["requires_human".into()],
            metadata_extra: json!({
                "checkpoint": input.checkpoint.checkpoint,
                "confirmed_by": input.checkpoint.confirmed_by,
                "confirmed_at": input.checkpoint.confirmed_at,
                "intention_id": input.intention_id,
                "workspace": input.workspace,
                "project": input.project
            }),
        },
    )
    .await
    {
        warn!(
            error=%err,
            trace_id=%req_ctx.request_id,
            "fuel emission failed for human.confirmed_intention"
        );
    }

    if let Some(issue) = &issue_id {
        if let Err(err) = fuel::emit_event(
            &state,
            &auth,
            FuelEventPayload {
                event_id: None,
                event_type: "intention.synced_to_linear".into(),
                trace_id: req_ctx.request_id.clone(),
                parent_event_id: None,
                outcome: "ok".into(),
                reason_codes: vec!["local_ok".into()],
                metadata_extra: json!({
                    "intention_id": input.intention_id,
                    "issue_id": issue,
                    "workspace": input.workspace,
                    "project": input.project
                }),
            },
        )
        .await
        {
            warn!(
                error=%err,
                trace_id=%req_ctx.request_id,
                "fuel emission failed for intention.synced_to_linear"
            );
        }
    }

    (
        StatusCode::OK,
        Json(crate::orchestration::OrchestrateResponse {
            request_id: req_ctx.request_id,
            output_schema: RESPONSE_ENVELOPE_SCHEMA,
            code247_request_id: intake.request_id,
            queue_id: Some(intake.ci.queue_id),
            issue_id,
            status: "accepted".into(),
        }),
    )
        .into_response()
}

pub async fn orchestrate_github_event(
    State(state): State<Arc<AppState>>,
    Extension(auth): Extension<AuthContext>,
    Extension(req_ctx): Extension<RequestContext>,
    Json(input): Json<crate::orchestration::OrchestrateGitHubEventRequest>,
) -> impl IntoResponse {
    let event = input.event_type.trim().to_ascii_lowercase();

    let (status, set_done, summary) = match event.as_str() {
        "pr.opened" => (
            "in_progress",
            false,
            input.summary.clone().unwrap_or_else(|| "PR opened".into()),
        ),
        "checks.passed" => (
            "validated",
            false,
            input
                .summary
                .clone()
                .unwrap_or_else(|| "CI checks passed".into()),
        ),
        "pr.merged" => (
            "merged",
            false,
            input.summary.clone().unwrap_or_else(|| "PR merged".into()),
        ),
        "deploy.completed" => {
            let is_success = input
                .status
                .as_deref()
                .map(|s| s.eq_ignore_ascii_case("success"))
                .unwrap_or(true);
            if is_success {
                (
                    "success",
                    true,
                    input
                        .summary
                        .clone()
                        .unwrap_or_else(|| "Deploy completed".into()),
                )
            } else {
                (
                    "failed",
                    false,
                    input
                        .summary
                        .clone()
                        .unwrap_or_else(|| "Deploy failed".into()),
                )
            }
        }
        "pr.changes_requested" => (
            "changes_requested",
            false,
            input
                .summary
                .clone()
                .unwrap_or_else(|| "Human requested changes".into()),
        ),
        _ => {
            return (
                StatusCode::BAD_REQUEST,
                Json(ErrorResponseV1::new(
                    Some(req_ctx.request_id.clone()),
                    "event_not_supported",
                    "event_type not supported",
                )),
            )
                .into_response();
        }
    };

    let mut evidence = Vec::<serde_json::Value>::new();
    if let Some(url) = input.pr_url.as_deref().filter(|v| !v.trim().is_empty()) {
        evidence.push(json!({"label":"pr", "url":url}));
    }
    if let Some(url) = input.ci_url.as_deref().filter(|v| !v.trim().is_empty()) {
        evidence.push(json!({"label":"ci", "url":url}));
    }
    if let Some(url) = input.deploy_url.as_deref().filter(|v| !v.trim().is_empty()) {
        evidence.push(json!({"label":"deploy", "url":url}));
    }

    let sync = match crate::orchestration::call_code247_sync(
        &state,
        &input.workspace,
        &input.project,
        &input.intention_id,
        status,
        &summary,
        serde_json::Value::Array(evidence),
        set_done,
    )
    .await
    {
        Ok(v) => v,
        Err(err) => {
            return (
                StatusCode::BAD_GATEWAY,
                Json(ErrorResponseV1::new(
                    Some(req_ctx.request_id.clone()),
                    "code247_sync_failed",
                    err.to_string(),
                )),
            )
                .into_response();
        }
    };

    let sync_item = sync.synced.first();
    let issue_id = sync_item.map(|i| i.issue_id.clone());
    let moved_to_done = sync_item.map(|i| i.moved_to_done).unwrap_or(false);
    let synced_intention_id = sync_item
        .map(|i| i.intention_id.clone())
        .unwrap_or_else(|| input.intention_id.clone());

    let event_type = match event.as_str() {
        "checks.passed" => "ci.completed",
        "pr.merged" => "merge.completed",
        "deploy.completed" => "deploy.completed",
        "pr.changes_requested" => "pr.review.human_required",
        _ => "code247.job.started",
    };

    if let Err(err) = fuel::emit_event(
        &state,
        &auth,
        FuelEventPayload {
            event_id: None,
            event_type: event_type.into(),
            trace_id: req_ctx.request_id.clone(),
            parent_event_id: None,
            outcome: if set_done {
                "ok".into()
            } else {
                "blocked".into()
            },
            reason_codes: vec!["local_ok".into()],
            metadata_extra: json!({
                "intention_id": synced_intention_id,
                "issue_id": issue_id,
                "event_type": input.event_type,
                "status": status,
                "moved_to_done": moved_to_done
            }),
        },
    )
    .await
    {
        warn!(
            error=%err,
            trace_id=%req_ctx.request_id,
            "fuel emission failed for github orchestration event"
        );
    }

    (
        StatusCode::OK,
        Json(crate::orchestration::OrchestrateResponse {
            request_id: req_ctx.request_id,
            output_schema: RESPONSE_ENVELOPE_SCHEMA,
            code247_request_id: sync.request_id,
            queue_id: None,
            issue_id,
            status: if moved_to_done || set_done {
                "done_synced".into()
            } else {
                "synced".into()
            },
        }),
    )
        .into_response()
}

pub async fn orchestrate_rollback(
    State(state): State<Arc<AppState>>,
    Extension(auth): Extension<AuthContext>,
    Extension(req_ctx): Extension<RequestContext>,
    Json(input): Json<crate::orchestration::OrchestrateRollbackRequest>,
) -> impl IntoResponse {
    if let Err(err) = crate::orchestration::ensure_yes_human_2(&input.checkpoint) {
        return (
            StatusCode::BAD_REQUEST,
            Json(ErrorResponseV1::new(
                Some(req_ctx.request_id.clone()),
                "checkpoint_invalid",
                err.to_string(),
            )),
        )
            .into_response();
    }

    if let Err(err) = fuel::emit_event(
        &state,
        &auth,
        FuelEventPayload {
            event_id: None,
            event_type: "rollback.requested".into(),
            trace_id: req_ctx.request_id.clone(),
            parent_event_id: None,
            outcome: "ok".into(),
            reason_codes: vec!["requires_human".into()],
            metadata_extra: json!({
                "intention_id": input.intention_id,
                "strategy": input.strategy,
                "reason": input.reason,
                "confirmed_by": input.checkpoint.confirmed_by
            }),
        },
    )
    .await
    {
        warn!(
            error=%err,
            trace_id=%req_ctx.request_id,
            "fuel emission failed for rollback.requested"
        );
    }

    let summary = format!(
        "Rollback requested by {} using strategy {}. Reason: {}",
        input.checkpoint.confirmed_by, input.strategy, input.reason
    );

    let mut evidence = Vec::<serde_json::Value>::new();
    if let Some(url) = input
        .rollback_url
        .as_deref()
        .filter(|v| !v.trim().is_empty())
    {
        evidence.push(json!({"label":"rollback", "url":url}));
    }

    let sync = match crate::orchestration::call_code247_sync(
        &state,
        &input.workspace,
        &input.project,
        &input.intention_id,
        "failed",
        &summary,
        serde_json::Value::Array(evidence),
        false,
    )
    .await
    {
        Ok(v) => v,
        Err(err) => {
            return (
                StatusCode::BAD_GATEWAY,
                Json(ErrorResponseV1::new(
                    Some(req_ctx.request_id.clone()),
                    "code247_sync_failed",
                    err.to_string(),
                )),
            )
                .into_response();
        }
    };

    let issue_id = sync.synced.first().map(|i| i.issue_id.clone());

    if let Err(err) = fuel::emit_event(
        &state,
        &auth,
        FuelEventPayload {
            event_id: None,
            event_type: "rollback.completed".into(),
            trace_id: req_ctx.request_id.clone(),
            parent_event_id: None,
            outcome: "ok".into(),
            reason_codes: vec!["local_ok".into()],
            metadata_extra: json!({
                "intention_id": input.intention_id,
                "issue_id": issue_id,
                "strategy": input.strategy,
                "status": "synced"
            }),
        },
    )
    .await
    {
        warn!(
            error=%err,
            trace_id=%req_ctx.request_id,
            "fuel emission failed for rollback.completed"
        );
    }

    (
        StatusCode::OK,
        Json(crate::orchestration::OrchestrateResponse {
            request_id: req_ctx.request_id,
            output_schema: RESPONSE_ENVELOPE_SCHEMA,
            code247_request_id: sync.request_id,
            queue_id: None,
            issue_id,
            status: "rollback_synced".into(),
        }),
    )
        .into_response()
}

async fn emit_fuel_pair(
    state: &AppState,
    auth: &AuthContext,
    opinion_event_type: &str,
    gate_event_type: &str,
    opinion_event_id: &str,
    trace_id: &str,
    reason_codes: &[String],
    opinion_extra: serde_json::Value,
    gate: &GateDecisionV1,
) -> anyhow::Result<()> {
    let _ = fuel::emit_event(
        state,
        auth,
        FuelEventPayload {
            event_id: Some(opinion_event_id.to_string()),
            event_type: opinion_event_type.to_string(),
            trace_id: trace_id.to_string(),
            parent_event_id: None,
            outcome: "ok".to_string(),
            reason_codes: reason_codes.to_vec(),
            metadata_extra: opinion_extra,
        },
    )
    .await?;

    let gate_outcome = match gate.decision.as_str() {
        "YES" => "ok",
        "NO" | "HUMAN" | "CLOUD" => "blocked",
        _ => "blocked",
    };

    let gate_extra = json!({
        "decision": gate.decision,
        "policy": gate.policy,
        "applied_rules": &gate.applied_rules
    });

    let _ = fuel::emit_event(
        state,
        auth,
        FuelEventPayload {
            event_id: None,
            event_type: gate_event_type.to_string(),
            trace_id: trace_id.to_string(),
            parent_event_id: Some(opinion_event_id.to_string()),
            outcome: gate_outcome.to_string(),
            reason_codes: reason_codes.to_vec(),
            metadata_extra: gate_extra,
        },
    )
    .await?;

    Ok(())
}
